language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r test-requirements.txt

script: py.test

notifications:
  email: false

git:
  depth: 1

branches:
  only:
  - master